
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdkstbmukhapmnasabjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNka3N0Ym11a2hhcG1uYXNhYmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDkzOTgsImV4cCI6MjA1OTY4NTM5OH0.tSuBxDNWkq_p5t-i6uolq9CBhyvuIUF-P7CsyqFyJDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'courseai-auth',
  },
});
